---
new_page_extension: md
auto_deploy: true
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  new_doc_ext: md
  templates:
  - page
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar build
    -v --baseurl=$DEPLOY_URL
  publish_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar build
    -v
  preview_env:
  - PHP_VERSION=7.2
  publish_env:
  - PHP_VERSION=7.2
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar
    serve -d --host=0.0.0.0 --port=8080
